ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
            modules = [ com.codersee.ApplicationKt.module ]
    }
}
jwt {
  secret   = "dev-super-secret"
  issuer   = "http://localhost/"
  audience = "my-audience"
  realm    = "My realm"

  # allow env overrides (optional)
  secret   = ${?SECRET}
  issuer   = ${?ISSUER}
  audience = ${?AUDIENCE}
  realm    = ${?REALM}
}