services:
  openldap:
    image: bitnamilegacy/openldap:2.6.10
    container_name: openldap
    hostname: ldap
    domainname: asd.msd.localhost            # FQDN becomes ldap.asd.msd.localhost
    environment:
      - LDAP_ROOT=dc=ldap,dc=asd,dc=msd,dc=localhost
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ENABLE_TLS=no
      - BITNAMI_DEBUG=true
    ports:
      - "1389:1389"                          # Bitnami uses 1389 for plain LDAP

    volumes:
      - ldap-data:/bitnami/openldap          # Bitnami data dir (persistent)
    healthcheck:
        test: [ "CMD-SHELL", "ldapsearch -x -H ldap://localhost:1389 -b dc=ldap,dc=asd,dc=msd,dc=localhost -s base '(objectclass=*)' >/dev/null 2>&1" ]
        interval: 5s
        timeout: 3s
        retries: 10
    networks:
      default:
        aliases:
          - ldap.asd.msd.localhost           # so other services resolve the FQDN

  app:
    build: .
    container_name: ktor-app
    depends_on:
      openldap:
        condition: service_healthy
      ml:
        condition: service_healthy
    environment:
      - SECRET=dev-super-secret
      - PORT=8080
      - UPLOAD_ROOT=/app/uploads
      - LDAP_URL=ldap://openldap:1389
      - LDAP_BASE_DN=ou=users,dc=ldap,dc=asd,dc=msd,dc=localhost
      - LDAP_BIND_DN=cn=admin,dc=ldap,dc=asd,dc=msd,dc=localhost
      - LDAP_BIND_PW=adminpassword
      - ML_URL=http://ml:8000
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      # uploads:/app/uploads if you only want to keep files in Docker volume and not have files
      # visible to host

  ml:
    build:
      context: .                     # repo root
      dockerfile: ml_server/Dockerfile
    environment:
      - MODEL_TASK=object-detection  # or image-to-text
      - MODEL_ID=hustvl/yolos-tiny   # or nlpconnect/vit-gpt2-image-captioning
      - TORCH_NUM_THREADS=2
      - HF_HOME=/root/.cache/huggingface
    working_dir: /app
    volumes:
      - ./uploads:/app/uploads
      - hf-cache:/root/.cache/huggingface
    expose:
      - "8000"                       # internal only (do NOT publish a host port)
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/healthz').getcode()==200 else sys.exit(1)"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 180s
    restart: unless-stopped

volumes:
  ldap-data:
  hf-cache: